#!/usr/bin/env python3
"""
Build the self-contained NaPTAN Data-Quality Explorer.

  data/naptan-stats.json  (generated by analyze.py from the official NaPTAN export)
  + index.template.html   ->  index.html   (real data embedded inline)

Regenerate the stats from the live national dataset:
  python3 analyze.py      # downloads ~97MB CSV from naptan.api.dft.gov.uk, recomputes
Then:
  python3 build.py
"""
import json, os
ROOT = os.path.dirname(os.path.abspath(__file__))
data = open(os.path.join(ROOT, "data", "naptan-stats.json")).read().strip()
tpl = open(os.path.join(ROOT, "index.template.html")).read()
out = tpl.replace("__DATA__", data)
open(os.path.join(ROOT, "index.html"), "w").write(out)
stats = json.loads(data)
print("built index.html (%d KB) — %s stops, %d map points, %d sample rows" % (
    len(out)//1024, format(stats["totalStops"], ","), len(stats["mapPoints"]), len(stats["sampleFlagged"])))
